{% set version = "2024b" %}

package:
  name: tzdata
  version: {{ version }}

source:
  - url: https://data.iana.org/time-zones/releases/tzdata{{ version }}.tar.gz
    sha256: 70e754db126a8d0db3d16d6b4cb5f7ec1e04d5f261255e4558a67fe92d39e550
  - url: https://data.iana.org/time-zones/releases/tzcode{{ version }}.tar.gz
    sha256: 5e438fc449624906af16a18ff4573739f0cda9862e5ec28d3bcb19cbaed0f672

build:
  number: 0
  noarch: generic
  # We build on osx (see conda-forge.yml) because sysroot_linux-<arch> depends on
  # tzdata; since this package is data-only, we don't want any of the run-exports
  ignore_run_exports_from:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
  host:
  run:

test:
  commands:
    - test -f "${PREFIX}/share/zoneinfo/leapseconds"
    - test -f "${PREFIX}/share/zoneinfo/leap-seconds.list"
    - test -f "${PREFIX}/share/zoneinfo/iso3166.tab"
    - test -f "${PREFIX}/share/zoneinfo/zone1970.tab"
    - test -f "${PREFIX}/share/zoneinfo/zone.tab"
    - test -f "${PREFIX}/share/zoneinfo/tzdata.zi"
    # Make sure we only package zoneinfo and nothing else.
    - |
      dirs="$(
        find "${PREFIX}" -mindepth 1 -maxdepth 2 \
        \! -path "${PREFIX}/share" \! -path "${PREFIX}/conda-meta*"
      )"
      test "${dirs}" = "${PREFIX}/share/zoneinfo"
    # Make sure we only package timezone information files.
    - |
      heads="$(
        find "${PREFIX}/share/zoneinfo" -type f \
          \! -name \*.zi \! -name \*.tab \! -name leapseconds \! -name leap-seconds.list \
          -exec sh -c 'head -c4 $1 && echo' sh {} \; \
          | uniq
      )"
      test "${heads}" = TZif

about:
  home: https://www.iana.org/time-zones
  dev_url: https://github.com/eggert/tz
  doc_url: https://data.iana.org/time-zones/tz-link.html
  license: LicenseRef-Public-Domain
  license_file: LICENSE
  summary: The Time Zone Database (called tz, tzdb or zoneinfo) data

  description: |
    The Time Zone Database (called tz, tzdb or zoneinfo) contains code 
    (the tzcode package) and data (this package) that represent the
    history of local time for many representative
    locations around the globe.  It is updated periodically to reflect
    changes made by political bodies to time zone boundaries, UTC offsets,
    and daylight-saving rules.

extra:
  recipe-maintainers:
    - ocefpaf
    - mbargull
    - pganssle
    - h-vetinari
